version: "3.2"

services:
  mysql:
    build:
      context: ./mysql
    container_name: mysql
    ports:
      - 3308:3306
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=my_strong_password
  php:
    build:
      context: ./php
    container_name: php
    ports:
      - 9000:9000
    volumes:
      - ./php/www:/var/www/html
    networks:
      - backend

  phpmyadmin:
    build:
      context: ./phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - mysql
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
    ports:
      - 6001:80
    networks:
      - backend

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile   
    container_name: nginx
    ports:
      - 9510:80
    restart: unless-stopped
    networks:
      - backend
      - frontend

networks:
  backend:
  frontend:
